# Generated by Django 3.1.3 on 2020-11-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField()),
                ('join_date', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('fees', models.IntegerField(default=200)),
            ],
        ),
    ]
